/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2023-11-27 10:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsp.park.Application;
import com.jsp.park.Post;
import java.util.List;

public final class so_002dregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.park.Application");
    _jspx_imports_classes.add("com.jsp.park.Post");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css\">\n");
      out.write("\n");
      out.write("    <link href=\"https://getbootstrap.com/docs/5.3/assets/css/docs.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"../cs s/Common.css\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 6.25em;\n");
      out.write("            border: none;\n");
      out.write("            resize: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen{\n");
      out.write("            background: #f3f3f3;\n");
      out.write("            height: 100vh;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-so{\n");
      out.write("            width: 25%;\n");
      out.write("            margin: 9rem auto;\n");
      out.write("            padding: 0;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-so .so-register{\n");
      out.write("            display: flex;\n");
      out.write("            flex-flow: row wrap; justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-so .so-register .px-4{\n");
      out.write("            width: 80%;\n");
      out.write("            margin: 2.5rem 0;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("        .fullScreen .web-so .so-register .px-4 .mb-3 {\n");
      out.write("            padding-bottom: 5%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-so .so-register .px-4 .mb-3:last-child{\n");
      out.write("            display: flex; flex-flow: row wrap;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*.fullScreen .web-so .so-register .cnsu-logo{*/\n");
      out.write("        /*    background: url(\"https://i.namu.wiki/i/8-appfHuJ_E2TrT83RDobLOh7O0dhLeFVvsC-1C_i9-mcycmpnFkDw_LBp-u5PsLO4G-n9NezdM1aDIB-e2YgQ.svg\") no-repeat center/contain;*/\n");
      out.write("\n");
      out.write("        /*    width: 15vw; height: 10vh;*/\n");
      out.write("        /*    margin: auto;*/\n");
      out.write("        /*}*/\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <title>jsp study</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"fullScreen p-3 m-0 border-0 bd-example m-0 border-0\">\n");
      out.write("    <div class=\"dropdown-menu web-so\">\n");
      out.write("        <div class=\"so-register\">\n");
      out.write("            <form method=\"post\" action=\"Sleepover\" class=\"px-4 py-3\">\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"start-so\" class=\"form-label\">외박시작일</label>\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"start-so\" name=\"Start_date\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"end-so\" class=\"form-label\">외박종료일</label>\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"end-so\" name=\"End_date\" >\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"reason-so\" class=\"form-label\">외박사유</label>\n");
      out.write("                    <textarea type=\"text\" class=\"form-control\" id=\"reason-so\" name=\"Reason\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"submit\"  value=\"신청\" class=\"btn btn-primary\">\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
