/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
<<<<<<< Updated upstream
 * Generated at: 2023-11-24 04:30:54 UTC
=======
 * Generated at: 2023-11-25 03:21:58 UTC
>>>>>>> Stashed changes
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ps_005fyoung;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usr_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/seon/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1700713400497L));
    _jspx_dependants.put("jar:file:/C:/Users/seon/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

<<<<<<< Updated upstream
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <link href=\"https://getbootstrap.com/docs/5.3/assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"../css/login.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <title>jsp study</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"fullScreen p-3 m-0 border-0 bd-example m-0 border-0\">\r\n");
      out.write("        <div class=\"dropdown-menu web-login\">\r\n");
      out.write("            <div class=\"cnsu-logo\"></div>\r\n");
      out.write("            <form method=\"post\" action=\"loginPro\" class=\"px-4 py-3\">\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"exampleDropdownFormEmail1\" class=\"form-label\">아이디</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"exampleDropdownFormEmail1\" name=\"id\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"exampleDropdownFormPassword1\" class=\"form-label\">패스워드</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"exampleDropdownFormPassword1\" name=\"password\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input\" id=\"dropdownCheck\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"dropdownCheck\">\r\n");
      out.write("                            로그인 정보 기억하기\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
=======
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css\">\n");
      out.write("\n");
      out.write("    <link href=\"https://getbootstrap.com/docs/5.3/assets/css/docs.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href=\"../css/Common.css\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        .fullScreen{\n");
      out.write("            background: #f3f3f3;\n");
      out.write("\n");
      out.write("            height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-login{\n");
      out.write("            width: 30%;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin: 6rem auto 9rem;\n");
      out.write("            padding: 0;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-login .login-child{\n");
      out.write("\n");
      out.write("            display: flex; flex-flow: column wrap;\n");
      out.write("            margin: 3.6rem auto;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-login .login-child .px-4 {\n");
      out.write("\n");
      out.write("            margin: 3.5rem 1.2rem;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fullScreen .web-login .login-child .cnsu-logo{\n");
      out.write("            background: url(\"https://i.namu.wiki/i/8-appfHuJ_E2TrT83RDobLOh7O0dhLeFVvsC-1C_i9-mcycmpnFkDw_LBp-u5PsLO4G-n9NezdM1aDIB-e2YgQ.svg\") no-repeat center/contain;\n");
      out.write("\n");
      out.write("            width: 15vw; height: 10vh;\n");
      out.write("            margin: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <title>jsp study</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"fullScreen p-3 m-0 border-0 bd-example m-0 border-0\">\n");
      out.write("    <div class=\"dropdown-menu web-login\">\n");
      out.write("        <div class=\"login-child\">\n");
      out.write("            <div class=\"cnsu-logo\"></div>\n");
      out.write("            <form class=\"px-4 py-3\">\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"exampleDropdownFormEmail1\" class=\"form-label\">아이디</label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"exampleDropdownFormEmail1\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"exampleDropdownFormPassword1\" class=\"form-label\">패스워드</label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"exampleDropdownFormPassword1\" >\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <div class=\"form-check\">\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input\" id=\"dropdownCheck\">\n");
      out.write("                        <label class=\"form-check-label\" for=\"dropdownCheck\">\n");
      out.write("                            로그인 정보 기억하기\n");
      out.write("                        </label>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <a class=\"btn btn-primary\" href=\"../MainPage/MainPage.jsp\">로그인</a>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
>>>>>>> Stashed changes
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
